// ============================================================================
// Frank — JSON file storage for sessions
// One JSON file per session, stored in ./data/sessions/<id>.json
// ============================================================================

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const DATA_DIR = process.env.DATA_DIR || path.join(__dirname, "..", "data");
const SESSIONS_DIR = path.join(DATA_DIR, "sessions");

export interface Session {
  id: string;
  createdAt: number;
  area: string;
  participant: {
    ageRange?: string; // "18-25", "26-35", "36-50", "51-65", "65+"
    gender?: string;
    postcode?: string;
    description?: string; // one-liner generated by AI after session
  };
  transcript: Array<{ timestamp: number; offsetMs: number; text: string }>;
  gpsLat: number;
  gpsLng: number;
  consentGiven: boolean;
  durationSeconds: number;
  audioPath?: string;
  analyzedIssues?: Array<{ issue: string; severity: number; quotes: string[] }>;
}

export async function ensureSessionsDir(): Promise<void> {
  await fs.mkdir(SESSIONS_DIR, { recursive: true });
}

export async function saveSession(session: Session): Promise<void> {
  await ensureSessionsDir();
  const filePath = path.join(SESSIONS_DIR, `${session.id}.json`);
  await fs.writeFile(filePath, JSON.stringify(session, null, 2), "utf-8");
}

export async function getSession(id: string): Promise<Session | null> {
  try {
    const filePath = path.join(SESSIONS_DIR, `${id}.json`);
    const content = await fs.readFile(filePath, "utf-8");
    return JSON.parse(content) as Session;
  } catch {
    return null;
  }
}

export async function listSessions(area?: string): Promise<Session[]> {
  await ensureSessionsDir();
  try {
    const files = await fs.readdir(SESSIONS_DIR);
    const sessions: Session[] = [];
    for (const file of files) {
      if (!file.endsWith(".json")) continue;
      try {
        const content = await fs.readFile(path.join(SESSIONS_DIR, file), "utf-8");
        const session = JSON.parse(content) as Session;
        if (!area || session.area.toLowerCase() === area.toLowerCase()) {
          sessions.push(session);
        }
      } catch {
        // skip malformed files
      }
    }
    return sessions.sort((a, b) => b.createdAt - a.createdAt);
  } catch {
    return [];
  }
}

export async function updateSessionTranscript(
  id: string,
  entry: { timestamp: number; offsetMs: number; text: string }
): Promise<Session | null> {
  const session = await getSession(id);
  if (!session) return null;
  session.transcript.push(entry);
  await saveSession(session);
  return session;
}
